#!/usr/bin/env python3
"""Migrate legacy Hall of Fame layout to source/build/dist structure."""

from __future__ import annotations

import argparse
import json
import shutil

from paths import BUILD_MINDFRAME_DIR, LEGACY_PERSONAS_DIR, SOURCE_PERSONAS_DIR


SOURCE_FILES = ["prompt.md", "memory.md", "examples.md", "regression.json"]


def migrate(*, dry_run: bool) -> None:
    if not LEGACY_PERSONAS_DIR.exists():
        print("Legacy personas directory not found, skipping source migration.")
        return

    SOURCE_PERSONAS_DIR.mkdir(parents=True, exist_ok=True)
    BUILD_MINDFRAME_DIR.mkdir(parents=True, exist_ok=True)

    for legacy_dir in sorted(LEGACY_PERSONAS_DIR.iterdir()):
        if not legacy_dir.is_dir():
            continue
        target_dir = SOURCE_PERSONAS_DIR / legacy_dir.name
        if not dry_run:
            target_dir.mkdir(parents=True, exist_ok=True)
        for filename in SOURCE_FILES:
            src = legacy_dir / filename
            dst = target_dir / filename
            if src.exists() and not dst.exists():
                print(f"Copy {src} -> {dst}")
                if not dry_run:
                    shutil.copy2(src, dst)
        persona_src = legacy_dir / "persona.json"
        persona_dst = target_dir / "persona.json"
        if persona_src.exists() and not persona_dst.exists():
            print(f"Transform {persona_src} -> {persona_dst} (inject schemaVersion)")
            if not dry_run:
                data = json.loads(persona_src.read_text(encoding="utf-8"))
                data.setdefault("schemaVersion", "1.0")
                persona_dst.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        # Legacy nuwa.md is intentionally not copied; mindframe is regenerated by pipeline.


def main() -> None:
    parser = argparse.ArgumentParser(description="Migrate to source/build/dist layout")
    parser.add_argument("--dry-run", action="store_true", help="Only print operations")
    args = parser.parse_args()
    migrate(dry_run=args.dry_run)
    if args.dry_run:
        print("Dry run complete.")
    else:
        print("Migration complete.")


if __name__ == "__main__":
    main()
